include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_fields: true
    use_super_parameters: true
    sized_box_for_whitespace: true
    prefer_single_quotes: true

analyzer:
  errors:
    invalid_annotation_target: ignore
  exclude:
    - lib/l10n/app_localizations*.dart
    - '**.g.dart'
